version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - .:/var/www/html
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
            - app
    mysql:
        image: mysql
        restart: unless-stopped
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: dbpass
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
        ports:
            - '3307:3306'
        volumes:
            - data:/var/lib/mysql
volumes:
    data:
